name: Staging Deployment

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://staging.procuregenius.autonomoslab.com
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"

      - name: Run tests (smoke test)
        run: |
          pytest tests/unit/ -v -m "not slow"

      - name: Build package
        run: python -m build

      - name: Configure watsonx credentials
        env:
          WATSONX_API_KEY: ${{ secrets.WATSONX_API_KEY_STAGING }}
          WATSONX_PROJECT_ID: ${{ secrets.WATSONX_PROJECT_ID_STAGING }}
        run: |
          mkdir -p config
          echo "WATSONX_API_KEY=$WATSONX_API_KEY" > config/.env.staging
          echo "WATSONX_PROJECT_ID=$WATSONX_PROJECT_ID" >> config/.env.staging
          echo "ENV=staging" >> config/.env.staging

      - name: Deploy to staging
        run: |
          python scripts/deploy-staging.py
        env:
          ENVIRONMENT: staging
          WATSONX_API_KEY: ${{ secrets.WATSONX_API_KEY_STAGING }}
          WATSONX_PROJECT_ID: ${{ secrets.WATSONX_PROJECT_ID_STAGING }}

      - name: Run integration tests
        run: |
          pytest tests/integration/ -v -m integration
        env:
          WATSONX_API_KEY: ${{ secrets.WATSONX_API_KEY_STAGING }}
          WATSONX_PROJECT_ID: ${{ secrets.WATSONX_PROJECT_ID_STAGING }}

      - name: Notify deployment status
        if: always()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          text: 'Staging deployment ${{ job.status }}'
          webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Create deployment summary
        if: success()
        run: |
          echo "## Staging Deployment Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **Environment**: staging" >> $GITHUB_STEP_SUMMARY
          echo "- **Commit**: ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Branch**: ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Deployed by**: ${{ github.actor }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Status**: ✅ Success" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Access staging: https://staging.procuregenius.autonomoslab.com" >> $GITHUB_STEP_SUMMARY
